# Generated by Django 6.0.1 on 2026-01-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cible', '0008_move_files_to_filetypes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='campaignentity',
            index=models.Index(fields=['year', 'semester'], name='idx_campaign_year_sem'),
        ),
        migrations.AddIndex(
            model_name='campaignentity',
            index=models.Index(fields=['status_id'], name='idx_campaign_status'),
        ),
        migrations.AddIndex(
            model_name='campaignentity',
            index=models.Index(fields=['installation_id'], name='idx_campaign_install'),
        ),
    ]
