# Generated by Django 6.0.1 on 2026-01-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cible', '0009_add_campaign_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fsecentity',
            index=models.Index(fields=['status_id'], name='idx_fsec_status'),
        ),
        migrations.AddIndex(
            model_name='fsecentity',
            index=models.Index(fields=['campaign_id'], name='idx_fsec_campaign'),
        ),
        migrations.AddIndex(
            model_name='fsecentity',
            index=models.Index(fields=['is_active'], name='idx_fsec_active'),
        ),
        migrations.AddIndex(
            model_name='fsecentity',
            index=models.Index(fields=['fsec_uuid'], name='idx_fsec_uuid'),
        ),
    ]
