# Generated by Django 6.0.1 on 2026-01-10 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cible', '0010_add_fsec_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsecdocumentsentity',
            name='step_type',
            field=models.CharField(choices=[('DESIGN', 'Design'), ('ASSEMBLY', 'Assemblage'), ('METROLOGY', 'Métrologie'), ('SEALING', 'Scellement'), ('PICTURES', 'Photos'), ('USABLE', 'Utilisable'), ('INSTALLED', 'Installé')], db_column='step_type', default='DESIGN', max_length=20),
        ),
        migrations.AddField(
            model_name='fsecdocumentsentity',
            name='step_uuid',
            field=models.UUIDField(blank=True, db_column='step_uuid', null=True),
        ),
        migrations.AddField(
            model_name='fsecteamsentity',
            name='step_type',
            field=models.CharField(choices=[('DESIGN', 'Design'), ('ASSEMBLY', 'Assemblage'), ('METROLOGY', 'Métrologie'), ('SEALING', 'Scellement'), ('PICTURES', 'Photos'), ('USABLE', 'Utilisable'), ('INSTALLED', 'Installé')], db_column='step_type', default='DESIGN', max_length=20),
        ),
        migrations.AddField(
            model_name='fsecteamsentity',
            name='step_uuid',
            field=models.UUIDField(blank=True, db_column='step_uuid', null=True),
        ),
        migrations.AlterField(
            model_name='fsecdocumentsentity',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DesignStepEntity',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comments', models.TextField(blank=True, max_length=4000, null=True)),
                ('fsec_version_id', models.ForeignKey(db_column='fsec_version_id', on_delete=django.db.models.deletion.CASCADE, related_name='design_steps', to='cible.fsecentity')),
            ],
            options={
                'db_table': 'DESIGN_STEP',
            },
        ),
        migrations.CreateModel(
            name='InstalledStepEntity',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shooting_date', models.DateField(blank=True, null=True)),
                ('preshooting_pressure', models.FloatField(blank=True, null=True)),
                ('experience_srxx', models.CharField(blank=True, max_length=50, null=True)),
                ('fsec_version_id', models.ForeignKey(db_column='fsec_version_id', on_delete=django.db.models.deletion.CASCADE, related_name='installed_steps', to='cible.fsecentity')),
            ],
            options={
                'db_table': 'INSTALLED_STEP',
            },
        ),
        migrations.CreateModel(
            name='UsableStepEntity',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('fsec_version_id', models.ForeignKey(db_column='fsec_version_id', on_delete=django.db.models.deletion.CASCADE, related_name='usable_steps', to='cible.fsecentity')),
            ],
            options={
                'db_table': 'USABLE_STEP',
            },
        ),
    ]
