# Generated by Django 6.0.1 on 2026-01-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cible', '0011_fsecdocumentsentity_step_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblystepentity',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assemblystepentity',
            name='completed_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assemblystepentity',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assemblystepentity',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designstepentity',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designstepentity',
            name='completed_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designstepentity',
            name='drawing_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='designstepentity',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designstepentity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designstepentity',
            name='specifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designstepentity',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fsecentity',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fsecentity',
            name='current_step',
            field=models.CharField(blank=True, help_text='Étape actuelle du workflow (design, assembly, metrology, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fsecentity',
            name='is_current_version',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='fsecentity',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fsecentity',
            name='version_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='installedstepentity',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installedstepentity',
            name='completed_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installedstepentity',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installedstepentity',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metrologystepentity',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metrologystepentity',
            name='completed_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metrologystepentity',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metrologystepentity',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picturesstepentity',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picturesstepentity',
            name='completed_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picturesstepentity',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='picturesstepentity',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sealingstepentity',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sealingstepentity',
            name='completed_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sealingstepentity',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sealingstepentity',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usablestepentity',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usablestepentity',
            name='completed_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usablestepentity',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usablestepentity',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='fsecentity',
            index=models.Index(fields=['fsec_uuid', 'is_current_version'], name='idx_fsec_current'),
        ),
        migrations.AddIndex(
            model_name='fsecentity',
            index=models.Index(fields=['current_step'], name='idx_fsec_step'),
        ),
        migrations.AddConstraint(
            model_name='fsecentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current_version', True)), fields=('fsec_uuid',), name='unique_current_version_per_fsec'),
        ),
    ]
