"""
Campaign Mapper - Data conversion functions.

This module provides mapping functions to convert Campaign data between
different layers: Entity (database) ↔ Bean (domain) ↔ API (JSON).
"""

from typing import Dict, Any
from uuid import UUID

from cible.domain.referential.models.campaign_bean import CampaignBean
from cible.repository.referential.models.campaign_entity import CampaignEntity


def campaign_mapper_entity_to_bean(entity: CampaignEntity) -> CampaignBean:
    """
    Convert Campaign Entity (Django Model) to Bean (domain model).

    Args:
        entity: Django ORM Campaign entity

    Returns:
        Campaign bean for use in business logic
    """
    return CampaignBean(
        uuid=entity.uuid,
        name=entity.name,
        year=entity.year,
        code=entity.code,
        description=entity.description,
        start_date=entity.start_date,
        end_date=entity.end_date,
        is_active=entity.is_active,
        created_at=entity.created_at,
        updated_at=entity.updated_at,
    )


def campaign_mapper_bean_to_entity(bean: CampaignBean) -> CampaignEntity:
    """
    Convert Campaign Bean (domain model) to Entity (Django Model).

    Args:
        bean: Campaign bean from business logic

    Returns:
        Django ORM Campaign entity ready for database operations

    Note:
        If bean.uuid is None, a new UUID will be generated by Django.
    """
    entity = CampaignEntity()

    if bean.uuid:
        entity.uuid = bean.uuid

    entity.name = bean.name
    entity.year = bean.year
    entity.code = bean.code
    entity.description = bean.description
    entity.start_date = bean.start_date
    entity.end_date = bean.end_date
    entity.is_active = bean.is_active

    return entity


def campaign_mapper_api_to_bean(data: Dict[str, Any]) -> CampaignBean:
    """
    Convert API JSON data to Campaign Bean.

    Args:
        data: Dictionary from JSON request body

    Returns:
        Campaign bean for use in business logic

    Example:
        >>> data = {
        ...     "name": "Campaign 2025",
        ...     "year": 2025,
        ...     "code": "C2025-01"
        ... }
        >>> bean = campaign_mapper_api_to_bean(data)
    """
    # Parse UUID if present
    uuid_value = None
    if "uuid" in data and data["uuid"]:
        uuid_value = UUID(data["uuid"]) if isinstance(data["uuid"], str) else data["uuid"]

    return CampaignBean(
        uuid=uuid_value,
        name=data.get("name", ""),
        year=data.get("year", 0),
        code=data.get("code", ""),
        description=data.get("description"),
        start_date=data.get("start_date"),
        end_date=data.get("end_date"),
        is_active=data.get("is_active", True),
    )


def campaign_mapper_bean_to_api(bean: CampaignBean) -> Dict[str, Any]:
    """
    Convert Campaign Bean to API JSON response.

    Args:
        bean: Campaign bean from business logic

    Returns:
        Dictionary ready for JSON serialization

    Example:
        >>> bean = CampaignBean(name="Test", year=2025, code="T2025")
        >>> api_data = campaign_mapper_bean_to_api(bean)
        >>> api_data["name"]
        'Test'
    """
    return {
        "uuid": str(bean.uuid) if bean.uuid else None,
        "name": bean.name,
        "year": bean.year,
        "code": bean.code,
        "description": bean.description,
        "start_date": bean.start_date.isoformat() if bean.start_date else None,
        "end_date": bean.end_date.isoformat() if bean.end_date else None,
        "is_active": bean.is_active,
        "created_at": bean.created_at.isoformat() if bean.created_at else None,
        "updated_at": bean.updated_at.isoformat() if bean.updated_at else None,
    }
