from django.core.management.base import BaseCommand

from cible.management.commands.database_util import insert_csv_into_table


class Command(BaseCommand):
    help = "Initialize database"

    def handle(self, *args, **options):
        insert_csv_into_table(
            self,
            "CAMPAIGN_STATUS",
            "cible/management/commands/campaign/campaign_status.csv",
        )
        insert_csv_into_table(
            self,
            "CAMPAIGN_TYPES",
            "cible/management/commands/campaign/campaign_types.csv",
        )
        insert_csv_into_table(
            self,
            "CAMPAIGN_INSTALLATIONS",
            "cible/management/commands/campaign/campaign_installations.csv",
        )
        insert_csv_into_table(
            self,
            "CAMPAIGN_ROLES",
            "cible/management/commands/campaign/campaign_roles.csv",
        )
        insert_csv_into_table(
            self,
            "CAMPAIGN_DOCUMENT_TYPES",
            "cible/management/commands/campaign/campaign_document_types.csv",
        )

        insert_csv_into_table(
            self,
            "CAMPAIGN_DOCUMENT_SUBTYPES",
            "cible/management/commands/campaign/campaign_document_subtypes.csv",
        ),
        insert_csv_into_table(
            self,
            "FSEC_CATEGORY",
            "cible/management/commands/fsec/fsec_category.csv",
        )
        insert_csv_into_table(
            self,
            "FSEC_STATUS",
            "cible/management/commands/fsec/fsec_status.csv",
        )
        insert_csv_into_table(
            self,
            "FSEC_RACK",
            "cible/management/commands/fsec/fsec_racks.csv",
        )
        insert_csv_into_table(
            self,
            "METROLOGY_MACHINE",
            "cible/management/commands/fsec/metrology_machine.csv",
        )
        insert_csv_into_table(
            self,
            "ASSEMBLY_BENCH",
            "cible/management/commands/fsec/fsec_assembly_benches.csv",
        )
        insert_csv_into_table(
            self,
            "FSEC_ROLES",
            "cible/management/commands/fsec/fsec_roles.csv",
        )
        insert_csv_into_table(
            self,
            "FSEC_TEAMS",
            "cible/management/commands/fsec/fsec_teams.csv",
        )
        insert_csv_into_table(
            self,
            "FSEC_DOCUMENT_TYPES",
            "cible/management/commands/fsec/fsec_document_types.csv",
        )
        insert_csv_into_table(
            self,
            "FSEC_DOCUMENT_SUBTYPES",
            "cible/management/commands/fsec/fsec_document_subtypes.csv",
        )
        insert_csv_into_table(
            self,
            "FSEC_DOCUMENTS",
            "cible/management/commands/fsec/fsec_documents.csv",
        )
        insert_csv_into_table(
            self,
            "ASSEMBLY_STEP",
            "cible/management/commands/fsec/steps/assembly_step.csv",
        )
        insert_csv_into_table(
            self,
            "METROLOGY_STEP",
            "cible/management/commands/fsec/steps/metrology_step.csv",
        )
        insert_csv_into_table(
            self,
            "PICTURES_STEP",
            "cible/management/commands/fsec/steps/pictures_step.csv",
        )
        insert_csv_into_table(
            self,
            "SEALING_STEP",
            "cible/management/commands/fsec/steps/sealing_step.csv",
        )
